### PR TITLE
Switch content type check to warning

### LINKED ISSUE #1: http provider too strict with application/json content type
_This issue was originally opened by @sebastien-prudhomme as hashicorp/terraform#15164. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version

0.9.7

### Affected Resource(s)

"http" datasource

### Terraform Configuration Files

```hcl
data "http" "openstack" {
  url = "http://169.254.169.254/openstack/latest/meta_data.json"
}
```

### Actual Behavior

Not working:

```
Error refreshing state: 1 error(s) occurred:

* data.http.main: 1 error(s) occurred:

* data.http.main: data.http.main: Content-Type is not a text type. Got: application/json; charset=UTF-8
```

In source code builtin/providers/http/data_source.go:

```go
func isContentTypeAllowed(contentType string) bool {
	allowedContentTypes := []*regexp.Regexp{
		regexp.MustCompile("^text/.+"),
		regexp.MustCompile("^application/json$"),
}
```

The regexp for "application/json" is too strict, as the charset can also be included by the web server

### PR DESCRIPTION
**Pull request by paultyng**
Fixes #1

### CODE REVIEW

File: internal/provider/data_source.go [hunk 1]
```diff
@@ -70,45 +69,51 @@ func dataSourceRead(d *schema.ResourceData, meta interface{}) error {
...
+		return append(diags, diag.Errorf("HTTP request error. Response code: %d", resp.StatusCode)...)
 	}
 
 	contentType := resp.Header.Get("Content-Type")
-	if contentType == "" || isContentTypeAllowed(contentType) == false {
-		return fmt.Errorf("Content-Type is not a text type. Got: %s", contentType)
+	if contentType == "" || isContentTypeText(contentType) == false {
+		diags = append(diags, diag.Diagnostic{
+			Severity: diag.Warning,
+			Summary:  "Content-Type is not recognized as a text type, got %q",
```
Comment (appilon) [inline internal/provider/data_source.go:85]:
```suggestion
			Summary:  fmt.Sprintf("Content-Type is not recognized as a text type, got %q", contentType),
```
However be aware that message seems a little off if `contentType == ""`

**Review by appilon — CHANGES_REQUESTED** [review]

**Review by appilon — APPROVED** [review]
